name: run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # đúng 4 giờ sáng mỗi ngày.

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: main
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run:  doppler run -p auto-create-group-telegram -c prod -- uv run python main.py

